### ISSUE TITLE
RuntimeError: derivative for to_dense is not implemented

### ISSUE THREAD

**Issue by tang0704** [limaosen0/AS-GCN#27]
Thanks for your code.

I have already pretrained AIM first and it's good.  When I trained the main pipleline by 
```
python main.py recognition -c config/as_gcn/ntu-xsub/train.yaml
```
I got this error:
```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    p.start()
  File "/home/lenovo/code/tang/AS-GCN/processor/processor.py", line 111, in start
    self.train(training_A=False)
  File "/home/lenovo/code/tang/AS-GCN/processor/recognition.py", line 167, in train
    loss1.backward()
  File "/home/lenovo/.conda/envs/tang0.4.0/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lenovo/.conda/envs/tang0.4.0/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: derivative for to_dense is not implemented

```

I don't know how to fix the error above. I would appreciate it if you could help me.

**Comment by tang0704** [comment]
The pytorch version I used above is 1.0.1. 

When I change it as 'readme.md' says, that is, 0.4.1, the code works.
