### ISSUE TITLE
TypeError: gendata() got an unexpected keyword argument 'part'

### ISSUE THREAD

**Issue by yanghhx** [limaosen0/AS-GCN#40]
when I run a commad "python ntu_gen_preprocess.py
xsub train".It appears the problem :Traceback (most recent call last):
  File "ntu_gen_preprocess.py", line 143, in <module>
    gendata(arg.data_path, out_path, arg.ignored_sample_path, benchmark=b, part=sn)
TypeError: gendata() got an unexpected keyword argument 'part'

**Comment by Noahhhhhhhhhhh** [comment]
> when I run a commad "python ntu_gen_preprocess.py
> xsub train".It appears the problem :Traceback (most recent call last):
> File "ntu_gen_preprocess.py", line 143, in
> gendata(arg.data_path, out_path, arg.ignored_sample_path, benchmark=b, part=sn)
> TypeError: gendata() got an unexpected keyword argument 'part'

Have you solved the problem

**Comment by Kevin0yue** [comment]
do you know how to solve this problem?

**Comment by YHY-10** [comment]
I have solved this problem by replacing "part" with "set_name"

**Comment by YHY-10** [comment]
By pressing "CTRL + P" on your keyboard , you can see the parameters you need.

**Comment by YHY-10** [comment]
> I have solved this problem by replacing "part" with "set_name"

**Comment by YHY-10** [comment]
> do you know how to solve this problem?
I have solved this problem by replacing "part" with "set_name"
By pressing "CTRL + P" on your keyboard , you can see the parameters you need.
