### ISSUE TITLE
I got some wrong as follows

### ISSUE THREAD

**Issue by aq08** [limaosen0/AS-GCN#7]
File "/AS-GCN/io.py", line 183, in import_class
    __import__(mod_str)
ModuleNotFoundError: No module named 'processor.demo'

**Comment by BigLazyPig** [comment]
Hello, this line is not important, you can comment it directly.
See here https://github.com/limaosen0/AS-GCN/issues/2

**Comment by wmingdao** [comment]
> File "/AS-GCN/io.py", line 183, in import_class
> **import**(mod_str)
> ModuleNotFoundError: No module named 'processor.demo'
Have you resolve this problem? thanks

**Comment by huangyibo1996** [comment]
If I comment it, another error will occur. 

Traceback (most recent call last):
  File "D:/PyCharmProjectsSet/AS-GCN/main.py", line 22, in <module>
    Processor = processors[arg.processor]
KeyError: None
